### ISSUE TITLE
Agregar Link de Overleaf

### ISSUE THREAD

**Issue by gustavoaca1997** [talassio/tesis-usb#1]
Subí el ejemplo de pregrado a Overleaf: https://es.overleaf.com/read/gfgzdmkkvpnk

Pero si los administradores de este repo pueden crear sus propios proyectos de Overleaf y mantenerlos sería bueno también.

**Comment by talassio** [comment]
Ahora Oveleaf tiene las plantillas en la galería.

 1. Pregrado: Tesis y Pasantías, https://www.overleaf.com/latex/templates/tesis-universidad-simon-bolivar-usb-pregrado/rbczxxywsypc
 2. Postgrado: Tesis, https://www.overleaf.com/latex/templates/tesis-universidad-simon-bolivar-postgrado/crskmcwnvwzy

Closes #1

**Comment by talassio** [comment]
Added to Overleaf gallery
